name: cord_cast
description: Discord audio streaming bot — Flutter desktop frontend.
publish_to: 'none'
version: 0.0.0+0

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  google_fonts: ^8.1.0
  path: ^1.9.1
  window_manager: ^0.5.1
  tray_manager: ^0.5.2
  package_info_plus: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/worker/
